name: 'Scan build'
description: 'Launch clang scan-build'
inputs:
  config-args:
    description: 'Bambu configure arguments'
    required: false
    default: ''
  report-dir:
    description: 'Scan build report directory'
    required: false
    default: './scanbuild-report'
  jobs:
    description: 'Parallel jobs'
    required: false
    default: '1'
outputs:
  report-dir:
    description: 'Scan build report directory'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    J: ${{inputs.jobs}}
  args:
    - ${{inputs.report-dir}}
    - ${{inputs.config-args}}
